# App-specific tweaks
source = ~/archy/default/hypr/apps/pip.conf
source = ~/archy/default/hypr/apps/browser.conf
source = ~/archy/default/hypr/apps/hyprshot.conf
source = ~/archy/default/hypr/apps/retroarch.conf
source = ~/archy/default/hypr/apps/steam.conf
source = ~/archy/default/hypr/apps/system.conf
source = ~/archy/default/hypr/apps/walker.conf
source = ~/archy/default/hypr/apps/1password.conf
source = ~/archy/default/hypr/apps/jetbrains.conf
